start_interview:
  description: >
    Start a job interview for the specified position and experience level.
    Consider the following parameters:
    - job_title: The position the candidate is interviewing for
    - experience_level: Junior, Mid-level, or Senior
    - interview_type: Technical or Behavioral
    - company_culture: Formal, Casual, or Balanced
    Begin with a professional introduction that sets the context and ask an
    appropriate opening question based on the interview type.
  expected_output: >
    A JSON object with the following structure:
    {
      "introduction": "Professional introduction text",
      "opening_question": "First interview question",
      "interview_context": {
        "job_title": "Software Engineer",
        "experience_level": "Mid-level",
        "interview_type": "Technical",
        "company_culture": "Balanced"
      }
    }
  agent: technical_interviewer

respond_to_answer:
  description: >
    Based on the interview history and the candidate's last answer, evaluate the response
    and ask an appropriate follow-up question. Consider:
    - The quality and completeness of the candidate's answer
    - Areas that need further exploration
    - The natural progression of the interview
    - Time management (typical interviews have 5-7 questions)
    
    **Interview History:** {{interview_history}}
    **Candidate's Last Answer:** {{user_response}}
    **Current Interview Phase:** {{current_phase}}
  expected_output: >
    A JSON object with the following structure:
    {
      "evaluation": "Brief assessment of the previous answer",
      "follow_up": "The next question to ask",
      "notes": "Internal notes on candidate performance (not shown to candidate)"
    }
  agent: technical_interviewer

review_interview:
  description: >
    Conduct a comprehensive review of the complete interview, evaluating the candidate's
    performance across multiple dimensions. Consider:
    - Technical/domain knowledge
    - Problem-solving approach
    - Communication skills
    - Cultural fit
    - Overall impression
    
    **Complete Interview Transcript:** {{interview_transcript}}
    **Job Requirements:** {{job_requirements}}
  expected_output: >
    A JSON object with the following structure:
    {
      "scores": {
        "technical_knowledge": 85,
        "problem_solving": 75,
        "communication": 90,
        "cultural_fit": 80,
        "overall": 82
      },
      "strengths": ["Strength 1", "Strength 2", "Strength 3"],
      "improvement_areas": ["Area 1", "Area 2", "Area 3"],
      "specific_feedback": "Detailed feedback with examples from the interview",
      "recommendation": "Hire/No Hire/Consider for different role"
    }
  agent: feedback_coach

prepare_custom_interview:
  description: >
    Create a customized interview plan based on the job description, required skills,
    and candidate background. Design a sequence of questions that will effectively
    evaluate the candidate's fit for the specific role.
    
    **Job Description:** {{job_description}}
    **Required Skills:** {{required_skills}}
    **Candidate Background:** {{candidate_background}}
  expected_output: >
    A JSON object with the following structure:
    {
      "interview_plan": {
        "introduction": "Planned introduction text",
        "technical_questions": ["Question 1", "Question 2", "Question 3"],
        "behavioral_questions": ["Question 1", "Question 2", "Question 3"],
        "role_specific_questions": ["Question 1", "Question 2", "Question 3"],
        "closing_questions": ["Question 1"]
      },
      "evaluation_criteria": {
        "key_skills_to_assess": ["Skill 1", "Skill 2", "Skill 3"],
        "behavioral_traits_to_observe": ["Trait 1", "Trait 2", "Trait 3"]
      }
    }
  agent: technical_interviewer