parse_resume:
  description: >
    Extract and normalize full text from the uploaded resume file (PDF),
    preserving section headers and bullet structure.
  expected_output: >
    A single string containing the cleaned, concatenated resume text.
  agent: resume_refiner_agent

refine_resume:
  description: >
    Analyze the parsed resume text and generate a comprehensive evaluation with scores and feedback.
    Evaluate the resume across four main categories:
    
    1. Format & Layout (0-100 points)
       - Übersichtlichkeit: klare Abschnitte, konsistenter Weißraum
       - Einheitliche Formatierung: Schriftgrößen, Bullet-Styles, Ränder
    
    2. Inhalt & Struktur (0-100 points)
       - Vollständige Kernabschnitte (Profil, Berufserfahrung, Ausbildung, Skills)
       - Logischer Aufbau und Fluss zwischen den Abschnitten
    
    3. Sprache & Stil (0-100 points)
       - Aktive, präzise Formulierungen
       - Rechtschreibung, Grammatik und Tonalität
    
    4. Ergebnis-Orientierung (0-100 points)
       - Fokus auf quantifizierbare Erfolge (KPIs, Zahlen, Prozentwerte)
       - Klare Herausstellung von Impact und Verantwortungsbereichen
    
    For each category, provide a score and specific feedback with improvement suggestions.
    Calculate an overall score as the weighted average of all categories.
  expected_output: >
    A JSON object with the exact structure:
    {
      "scores": {
        "format_layout": 75,
        "inhalt_struktur": 80,
        "sprache_stil": 65,
        "ergebnis_orientierung": 70,
        "overall": 72.5
      },
      "feedback": {
        "format_layout": ["Feedback point 1", "Feedback point 2"],
        "inhalt_struktur": ["Feedback point 1", "Feedback point 2"],
        "sprache_stil": ["Feedback point 1", "Feedback point 2"],
        "ergebnis_orientierung": ["Feedback point 1", "Feedback point 2"]
      }
    }
    
    The response must be valid JSON with no text outside this structure.
  agent: resume_refiner_agent

match_resume:
  description: >
    Compare the resume content against a given job description, compute a match score,
    and identify the top 5 missing or underrepresented keywords. Offer concrete wording suggestions.
  expected_output: >
    An object with:
      - match_score: float between 0.0 and 1.0
      - suggestions: array of up to 5 strings recommending keyword additions or rephrases
  agent: resume_refiner_agent